// =============================================================================
// sobel_filter_learned.v
//
// Pipelined Sobel filter with ML-LEARNED kernel weights.
// Kernel weights are parameters — generated by train_sobel.py and loaded here.
//
// Drop-in replacement for sobel_filter_pipelined.v.
// Same port interface, same 3-stage pipeline.
// =============================================================================

module sobel_filter_learned #(
    parameter DATA_WIDTH = 8,
    parameter IMG_WIDTH  = 512,

    // -------------------------------------------------------------------------
    // ML-LEARNED KERNEL WEIGHTS  (auto-generated by train_sobel.py)
    // Row-major order: index 0=p00, 1=p01, 2=p02,
    //                        3=p10, 4=p11, 5=p12,
    //                        6=p20, 7=p21, 8=p22
    //
    // Default values = standard Sobel (replaced at build time with learned ones)
    // -------------------------------------------------------------------------
    parameter signed [4:0] K_GX_0 = -5'd1,  // p00
    parameter signed [4:0] K_GX_1 =  5'd0,  // p01
    parameter signed [4:0] K_GX_2 =  5'd1,  // p02
    parameter signed [4:0] K_GX_3 = -5'd2,  // p10
    parameter signed [4:0] K_GX_4 =  5'd0,  // p11
    parameter signed [4:0] K_GX_5 =  5'd2,  // p12
    parameter signed [4:0] K_GX_6 = -5'd1,  // p20
    parameter signed [4:0] K_GX_7 =  5'd0,  // p21
    parameter signed [4:0] K_GX_8 =  5'd1,  // p22

    parameter signed [4:0] K_GY_0 = -5'd1,  // p00
    parameter signed [4:0] K_GY_1 = -5'd2,  // p01
    parameter signed [4:0] K_GY_2 = -5'd1,  // p02
    parameter signed [4:0] K_GY_3 =  5'd0,  // p10
    parameter signed [4:0] K_GY_4 =  5'd0,  // p11
    parameter signed [4:0] K_GY_5 =  5'd0,  // p12
    parameter signed [4:0] K_GY_6 =  5'd1,  // p20
    parameter signed [4:0] K_GY_7 =  5'd2,  // p21
    parameter signed [4:0] K_GY_8 =  5'd1   // p22
)(
    input  wire                   clk,
    input  wire                   rst_n,
    input  wire [DATA_WIDTH-1:0]  pixel_in,
    input  wire                   pixel_valid,
    output reg  [DATA_WIDTH+3:0]  edge_out,
    output reg                    edge_valid
);

// ============================================================
// LINE BUFFERS
// ============================================================
reg [DATA_WIDTH-1:0] line1 [0:IMG_WIDTH-1];
reg [DATA_WIDTH-1:0] line2 [0:IMG_WIDTH-1];

integer i;
initial begin
    for (i = 0; i < IMG_WIDTH; i = i + 1) begin
        line1[i] = 0;
        line2[i] = 0;
    end
end

// ============================================================
// 3×3 WINDOW REGISTERS
// ============================================================
reg [DATA_WIDTH-1:0] p00, p01, p02;
reg [DATA_WIDTH-1:0] p10, p11, p12;
reg [DATA_WIDTH-1:0] p20, p21, p22;

integer col, row;
wire window_valid = (row >= 2 && col >= 2 && pixel_valid);

// ============================================================
// STAGE 0: WINDOW GENERATION
// ============================================================
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        col <= 0; row <= 0;
        p00<=0; p01<=0; p02<=0;
        p10<=0; p11<=0; p12<=0;
        p20<=0; p21<=0; p22<=0;
    end else if (pixel_valid) begin
        line2[col] <= line1[col];
        line1[col] <= pixel_in;

        p00 <= p01; p01 <= p02; p02 <= line2[col];
        p10 <= p11; p11 <= p12; p12 <= line1[col];
        p20 <= p21; p21 <= p22; p22 <= pixel_in;

        if (col == IMG_WIDTH-1) begin
            col <= 0;
            row <= row + 1;
        end else
            col <= col + 1;
    end
end

// ============================================================
// STAGE 1: Gx, Gy  —  PARAMETERIZED dot product (ML weights)
// ============================================================
reg v1, v2;
reg signed [DATA_WIDTH+5:0] gx, gy;   // extra bits for kernel multiply

// Extend pixel values to signed before multiplying
wire signed [DATA_WIDTH:0] sp00 = {1'b0, p00};
wire signed [DATA_WIDTH:0] sp01 = {1'b0, p01};
wire signed [DATA_WIDTH:0] sp02 = {1'b0, p02};
wire signed [DATA_WIDTH:0] sp10 = {1'b0, p10};
wire signed [DATA_WIDTH:0] sp11 = {1'b0, p11};
wire signed [DATA_WIDTH:0] sp12 = {1'b0, p12};
wire signed [DATA_WIDTH:0] sp20 = {1'b0, p20};
wire signed [DATA_WIDTH:0] sp21 = {1'b0, p21};
wire signed [DATA_WIDTH:0] sp22 = {1'b0, p22};

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        gx <= 0; gy <= 0; v1 <= 0;
    end else begin
        // Full general dot product — weights come from ML parameters
        gx <= K_GX_0*sp00 + K_GX_1*sp01 + K_GX_2*sp02
            + K_GX_3*sp10 + K_GX_4*sp11 + K_GX_5*sp12
            + K_GX_6*sp20 + K_GX_7*sp21 + K_GX_8*sp22;

        gy <= K_GY_0*sp00 + K_GY_1*sp01 + K_GY_2*sp02
            + K_GY_3*sp10 + K_GY_4*sp11 + K_GY_5*sp12
            + K_GY_6*sp20 + K_GY_7*sp21 + K_GY_8*sp22;

        v1 <= window_valid;
    end
end

// ============================================================
// STAGE 2: ABSOLUTE VALUE + MAGNITUDE
// ============================================================
wire [DATA_WIDTH+5:0] abs_gx = gx[DATA_WIDTH+5] ? (~gx + 1) : gx;
wire [DATA_WIDTH+5:0] abs_gy = gy[DATA_WIDTH+5] ? (~gy + 1) : gy;

reg [DATA_WIDTH+3:0] mag;

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        mag <= 0; v2 <= 0;
    end else begin
        // Shift right by 3 to undo the ×8 quantization scale factor
        mag <= (abs_gx + abs_gy) >> 3;
        v2  <= v1;
    end
end

// ============================================================
// STAGE 3: OUTPUT REGISTER
// ============================================================
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        edge_out   <= 0;
        edge_valid <= 0;
    end else begin
        edge_out   <= mag;
        edge_valid <= v2;
    end
end

endmodule
